### ISSUE TITLE
Extract Knot.x version in one place

### ISSUE THREAD

**Issue by tomaszmichalak** [Knotx/knotx-starter-kit#2]
**Is your feature request related to a problem? Please describe.**
We want to be able to easily adapt Starter Kit to project requirements. We use Knot.x as dependency in:
- custom modules (`modules/custom-action`, `modules/custom-handler`)
- Dockerfile (`docker/Dockerfile`)
- common Gradle scripts (`gradle/javaAndUnitTests.gradle.kts`)

We want to specify the Knot.x version once and use in all places.

The current solution use naive strategy that use the local variable `val knotxVersion = "2.0.0-SNAPSHOT"`.

**Comment by pun-ky** [comment]
to be able to use variable almost anywhere in gradle.build.kts you could put version into buildSrc/ class being precompiled before build runs

https://github.com/Cognifide/gradle-aem-multi/blob/develop/buildSrc/src/main/kotlin/build.kt#L3
then reference it by https://github.com/Cognifide/gradle-aem-multi/blob/develop/aem/gradle/artifacts.gradle.kts#L45

ensure having `kotlin-dsl` plugin applied in buildSrc to have it working

**Comment by malaskowski** [comment]
Fixed in #7
